Fixed a bug that appeared when the plugin name had the word "dir" in it. Also, now functions are used instead of process substitution.

diff --git a/bin/zplug-dir b/bin/zplug-dir
--- a/bin/zplug-dir
+++ b/bin/zplug-dir
@@ -7,35 +7,31 @@
 PLUGIN_NAME="$1"
 PLUGIN_DIR=""
 
-if [[ -z ${PLUGIN_NAME} ]]; then
-    echo 'zplug-dir: no plugin name provided' && exit 1
-fi
-
-if ! command -v zplug>/dev/null; then
+if ! __zplug::core::arguments::none>/dev/null 2>&1; then
     # `zplug` not sourced, possibly because
     # script running in non-interactive and
-    # single-command shell. You can avoid
-    # this by sourcing '$ZPLUG_HOME/init.zsh'
-    # after checking that your shell is login
-    # or interactive with '-o i' conditional:
-    # [[ ! -o i ]] && echo 'non interactive'
-
+    # single-command shell.
     if [[ -n "$ZPLUG_HOME" && -e "$ZPLUG_HOME"/init.zsh ]]; then
         source "$ZPLUG_HOME"/init.zsh
     else
-        echo 'zplug-dir: zplug not found, maybe $ZPLUG_HOME not set?'
-        exit 1
+        echo "zplug-dir: zplug not found, maybe \$ZPLUG_HOME not set?\n" && \
+            exit 1
     fi
 fi
 
-if ! zplug check ${PLUGIN_NAME} ; then
-    echo "zplug-dir: plugin not found - '${PLUGIN_NAME}'" && exit 1
+if [[ -z ${PLUGIN_NAME} ]]; then
+    __zplug::io::print::f "--error" "zplug-dir: no plugin name provided\n" && \
+        exit 1
 fi
 
-PLUGIN_DIR=$(zplug info $PLUGIN_NAME | grep 'dir' | cut -d' ' -f 3 | tr -d '\042')
-
-if [[ -n "${PLUGIN_DIR}" ]]; then
-    printf "%s\n" "${PLUGIN_DIR}" | sed -E $'s,\x1b\\[[0-9;]*[a-zA-Z],,g'
+if ! __zplug::base::base::zpluged "${PLUGIN_NAME}"; then
+    __zplug::io::print::f "--error" \
+        "zplug-dir: plugin not found - '${PLUGIN_NAME}'\n" && exit 1
 else
-    exit 1
+    PLUGIN_INFO=$(sed -E $'s,\x1b\\[[0-9;]*[a-zA-Z],,g' \
+        <(__zplug::core::core::run_interfaces "info" "${PLUGIN_NAME}"))
+    PLUGIN_DIR=$(grep -E '^\- dir:' <(echo $PLUGIN_INFO) | cut -d' ' -f 3 | \
+        tr -d '\042')
+
+    [[ -n "${PLUGIN_DIR}" ]] && printf "%s\n" "${PLUGIN_DIR}" || exit 1
 fi
